import CirclePacking.Basic
import CirclePacking.Certificate
import CirclePacking.Angle
import CirclePacking.Angular
import CirclePacking.CertificateFormat
import CirclePacking.CosineCertificate
import CirclePacking.CosineTaylor
import CirclePacking.CornerBound
import CirclePacking.SevenNineAngleData
import CirclePacking.SevenNine
import CirclePacking.SevenNineAngleProofs
import CirclePacking.SevenNineCoverage
import CirclePacking.FiniteOptimality
import CirclePacking.SevenNineFiniteOptimality
import CirclePacking.AngularCellCertificate
import CirclePacking.GeometricAngle
import CirclePacking.CyclicGap
import CirclePacking.PolarAngle
import CirclePacking.Optimality
import CirclePacking.StressCertificate
import CirclePacking.OptimalitySmokeTest
import CirclePacking.ParametricOptimality
import CirclePacking.GlobalAnchorRadius
import CirclePacking.FifteenCertificate
import CirclePacking.FifteenStageZero
import CirclePacking.FifteenStageZeroGeometry
import CirclePacking.FifteenTickSoundness
import CirclePacking.FifteenCycleSoundness
import CirclePacking.FifteenPackingAngleOrder
import CirclePacking.FifteenPackingPolarCoordinates
import CirclePacking.FifteenPackingSortedGeometry
import CirclePacking.FifteenPackingCycleEdgeGeometry
import CirclePacking.FifteenPackingCycleBridge
import CirclePacking.FifteenTickSymmetry
import CirclePacking.FifteenPackingCycleExclusion
import CirclePacking.FifteenLocalBarrierRigidity
import CirclePacking.FifteenLocalTaylor
import CirclePacking.FifteenTouchAngleDerivatives
import CirclePacking.FifteenTouchAngleTaylor
import CirclePacking.FifteenLocalBarrierAnalytic
import CirclePacking.FifteenLocalBarrierCycle
import CirclePacking.FifteenCandidateAngles
import CirclePacking.FifteenCandidateDetour
import CirclePacking.FifteenCandidateLocalBarrier
import CirclePacking.FifteenCandidateBounds

/-!
# Formal algebraic core for unequal-circle packing

The finite replay is paired with explicit angle-enclosure proofs in
`CirclePacking.SevenNineAngleProofs`.  The geometric implication from an
arbitrary `Packing` to the analytic radial bounds, and the finite-choice
coverage theorem for the radial boxes, are in
`CirclePacking.SevenNineCoverage`.  The remaining numerical boundary is the
external generation of the MPFI-exported rational data; its endpoint
comparisons are replayed by the coverage file.
-/
