name = "unequalCircleProof"
defaultTargets = ["CirclePacking"]

[package]
name = "unequalCircleProof"
version = "0.1.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "d13f23b723b8a846827a245b89c10fc7d3f11612"

[[lean_lib]]
name = "CirclePacking"
